name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Test My Project
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
	  projectPath: PATHHERE
          githubToken: ${{ secrets.GITHUB_TOKEN }}
